// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIzTpLIjWIVpeMwTqimXPMcw5JQ5HgEA',
    appId: '1:1076656034930:web:32a0a67833be3f371b9eeb',
    messagingSenderId: '1076656034930',
    projectId: 'cardapiodigital-amostra',
    authDomain: 'cardapiodigital-amostra.firebaseapp.com',
    storageBucket: 'cardapiodigital-amostra.appspot.com',
    measurementId: 'G-DES82YK8LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpIAexcq_Shc6gU2W1dZLa2KVCvNEbz4',
    appId: '1:1076656034930:android:48abda674799bd321b9eeb',
    messagingSenderId: '1076656034930',
    projectId: 'cardapiodigital-amostra',
    storageBucket: 'cardapiodigital-amostra.appspot.com',
  );
}
